/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedMapProperties = {
    minZoom: -6,
    maxZoom: 0,
    defaultZoom: 0,
    imageFormat: "jpeg",
    minRegionX: -17,
    minRegionZ: -17,
    maxRegionX: 26,
    maxRegionZ: 19,
    worldName: "NAC20250322",
    background: "",
    markers: new Array()
}
