/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedMapProperties = {
    minZoom: -6,
    maxZoom: 0,
    defaultZoom: 0,
    imageFormat: "webp",
    minRegionX: -17,
    minRegionZ: -17,
    maxRegionX: 27,
    maxRegionZ: 19,
    worldName: "NAC20250720",
    background: "",
    markers: new Array()
}
